Update olcPixelGameEngine.h
Added an #include for assert.h to fix compilation error 

./olcPixelGameEngine.h:4856:13: error: use of undeclared identifier 'assert'
            assert(resultAddMethod);
            ^

which appeared after updating to macOS 10.4 Sonoma.